version: "3.8"
services:
  webots:
    build:
      context: .devcontainer
      target: devcontainer
    ports:
      - 1234:1234
    environment:
      - WEBOTS_SHARED_FOLDER=/Users/deweykai/repos/ws_dev/src/tmp:/home/ws/src/tmp
    volumes:
      - .:/home/ws/src/haql-rover
