ekf_node_odom:
  ros__parameters:
    # update frequency
    frequency: 30.0

    # timeout period for sensors
    sensor_timeout: 0.1

    # is the ground flat
    two_d_mode: false

    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: odometry/wheel
    odom0_config: [true, true, true,
                   false, false, false,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 2

    imu0: imu/data
    imu0_config: [false, false, false, # linear
                  false, false, true, # angular
                  false, false, false, # linear velocity
                  true, true, true, # angular velocity
                  true, true, true] # linear acceleration
    imu0_remove_gravitational_acceleration: true

    use_control: false


    # process_noise_covariance: [1e-3, 1e-3, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    # initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


ekf_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    odom0: odometry/wheel
    odom0_config: [true, true, false,
                false, false, true,
                false, false, false,
                false, false, true,
                false, false, false]
    odom0_queue_size: 2
    odom0_differential: true

    odom1: odometry/gps
    odom1_config: [true, true, true,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
    odom1_queue_size: 2

    imu0: imu/data
    imu0_config: [false, false, false, # linear
                  false, false, true, # angular
                  false, false, false, # linear velocity
                  true, true, true, # angular velocity
                  true, true, true] # linear acceleration
    imu0_queue_size: 2
    imu0_remove_gravitational_acceleration: true

    use_control: false

    # process_noise_covariance: [1.0, 1.0, 1e-3, 0.3, 0.3, 0.01, 0.5, 0.5, 0.1, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

    # initial_estimate_covariance: [1.0, 1.0, 1e-9, 1.0, 1.0, 1e-9, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 30.0

    yaw_offset: 1.57079632679
    zero_altitude: false
    broadcast_cartesian_transform: true
    publish_filtered_gps: false
    use_odometry_yaw: false
    wait_for_datum: false