version: "3.8"
services:
  devcontainer:
    build:
      context: .
      target: devcontainer
    environment:
      - DISPLAY=unix:0
      - WEBOTS_SHARED_FOLDER=/Users/deweykai/repos/ws_dev/src/tmp:/home/ws/src/tmp
    volumes:
      - .:/home/ws/src/haql-rover
