controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    right_wheel_names: ["BackLeftWheel", "MiddleLeftWheel", "FrontLeftWheel"]
    left_wheel_names: ["BackRightWheel", "MiddleRightWheel", "FrontRightWheel"]

    wheel_separation: 0.52
    wheel_radius: 0.060

    wheels_per_side: 3

    # pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.5

    use_stamped_vel: false
    base_frame_id: base_link
    odom_frame_id: odom
    open_loop: false
    position_feedback: true
    enable_odom_tf: false

    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 1.2
        max_acceleration: 3.0

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 0.7
        max_acceleration: 2.5


    # cmd_vel_timeout: 500 # ms
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10