controller_manager:
  ros__parameters:
    update_rate: 50 # hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bodenbot_controller:
      type: diff_drive_controller/DiffDriveController


bodenbot_controller:
  ros__parameters:
    right_wheel_names:
        - "right_wheel_1_link_joint"
        - "right_wheel_2_link_joint"
        - "right_wheel_3_link_joint"
    left_wheel_names:
        - "left_wheel_1_link_joint"
        - "left_wheel_2_link_joint"
        - "left_wheel_3_link_joint"

    wheel_separation: 0.75
    wheel_radius: 0.13

    wheels_per_side: 3

    # pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: base_link
    odom_frame_id: odom
    open_loop: false
    position_feedback: true
    enable_odom_tf: false

    linear:
      x:
        has_velocity_limits: false
        has_acceleration_limits: false
        max_velocity: 1.0
        max_acceleration: 1.0

    angular:
      z:
        has_velocity_limits: false
        has_acceleration_limits: false
        max_velocity: 1.0
        max_acceleration: 1.0


    # cmd_vel_timeout: 500 # ms
    # publish_limited_velocity: true
    # velocity_rolling_window_size: 10